#!/bin/bash
# Music Jungle audio acquisition: downloads free/CC-licensed samples listed in
# /tmp/mjmanifest.tsv (generated by scripts/pick-samples.py) and converts to
# small mono MP3s in public/assets/audio/instruments/.
set -u
OUT="$(dirname "$0")/../public/assets/audio/instruments"
mkdir -p "$OUT" /tmp/mjraw

conv() { # in out maxsecs
  ffmpeg -y -loglevel error -i "$1" -ac 1 -ar 32000 -codec:a libmp3lame -b:a 96k -t "$3" \
    -af "afade=t=out:st=$(python3 -c "print(max(0,$3-0.6))"):d=0.6" "$2" && echo "OK $2" || echo "FAIL $2 <- $1"
}

fail=0
while IFS=$'\t' read -r id src secs; do
  case "$src" in
    file:*) in_file="${src#file:}";;
    url:*)
      in_file="/tmp/mjraw/$(echo "${src#url:}" | md5 -q).bin"
      [ -s "$in_file" ] || curl -sL "${src#url:}" -o "$in_file"
      ;;
  esac
  if [ ! -s "$in_file" ]; then echo "MISS $id"; fail=1; continue; fi
  conv "$in_file" "$OUT/$id.mp3" "$secs"
done < /tmp/mjmanifest.tsv

echo "--- DONE fail=$fail"
du -sh "$OUT"; ls "$OUT" | wc -l